services:
  recording:
    build:
      context: ./recording
    container_name: wbor-archiver-recorder
    restart: always
    volumes:
      - ./archive:/archive
    environment:
      - STATION_ID
      - STREAM_URL
      - ARCHIVE_DIR
      - SEGMENT_DURATION_SECONDS
      - TZ
    logging:
      driver: "json-file"
      options:
        max-size: "50m" # Max log file size before rotation (50MB)
        max-file: "3" # Keep last 3 rotated log files
    networks:
      - wbor-network
  
  archive-watchdog:
    build:
      context: ./archive-watchdog
    container_name: wbor-archiver-watchdog
    restart: always
    volumes:
      - ./archive:/archive
    environment:
      - ARCHIVE_DIR
      - SEGMENT_DURATION_SECONDS
      - TZ
    logging:
      driver: "json-file"
      options:
        max-size: "50m" # Max log file size before rotation (50MB)
        max-file: "3" # Keep last 3 rotated log files
    networks:
      - wbor-network
  # api:
  #   build:
  #     context: ./backend
  #   container_name: wbor-archiver-backend
  #   restart: unless-stopped
  #   volumes:
  #     - ./archive:/archive:ro  # The API only needs read-only permission
  #   ports:
  #     - "8000:8000"  # For local development
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
  #     interval: 30s
  #     timeout: 5s
  #     retries: 3
  #     start_period: 10s
  #   networks:
  #     - wbor-network

  # web:
  #   build:
  #     context: ./web
  #   container_name: wbor-archiver-web
  #   restart: unless-stopped
  #   ports:
  #     - "3000:80" # Direct local access for debugging
  #   depends_on:
  #     - api
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
  #     interval: 30s
  #     timeout: 5s
  #     retries: 3
  #     start_period: 10s
  #   networks:
  #     - wbor-network

  # proxy:
  #   build:
  #     context: ./proxy
  #   container_name: wbor-archiver-proxy
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - api
  #     - web
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
  #     interval: 30s
  #     timeout: 5s
  #     retries: 3
  #     start_period: 10s
  #   networks:
  #     - wbor-network

networks:
  wbor-network:
    driver: bridge
