@startuml Archiver Workflow

start

:Recording Service captures audio segments;
:Write segments to Archive Directory;

if (Segment completed?) then (yes)
    :Watchdog organizes segment in appropriate subdirectory (YYYY/MM/DD);
    :Watchdog notifies Backend via RabbitMQ;
    :Backend indexes segment & metadata in Postgres;
endif

:User requests a recording;
:Copy segment(s) to temporary directory on host disk;
if (Single segment requested?) then (yes)
    :Serve download;
else (no)
    :Concatenate segments with FFmpeg;
    :Serve gapless recording from host disk;
endif

stop

@enduml
